# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CppNormKern <- function(x2, y2, Di, pi) {
    .Call('Cppfft4_CppNormKern', PACKAGE = 'Cppfft4', x2, y2, Di, pi)
}

CppReflFunc <- function(Pop) {
    .Call('Cppfft4_CppReflFunc', PACKAGE = 'Cppfft4', Pop)
}

CppshiftmatFunc <- function(Mat) {
    .Call('Cppfft4_CppshiftmatFunc', PACKAGE = 'Cppfft4', Mat)
}

